# Generated by Django 5.1.3 on 2024-12-01 09:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bk_id', models.CharField(max_length=255, unique=True)),
                ('bk_name', models.CharField(max_length=255)),
                ('bk_item_num', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vc_id', models.CharField(max_length=255, unique=True)),
                ('vc_vocabulary', models.CharField(max_length=255)),
                ('vc_phonetic_uk', models.CharField(max_length=255)),
                ('vc_phonetic_us', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='RelationBookWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bv_id', models.CharField(max_length=255, unique=True)),
                ('bv_book_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.book')),
                ('bv_voc_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.word')),
            ],
        ),
        migrations.CreateModel(
            name='WordTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('translation', models.CharField(max_length=255)),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.word')),
            ],
        ),
    ]
